### ISSUE TITLE
[Suggestion] Add another nice option

### ISSUE THREAD

**Issue by MbtMarco** [Natanaelel/enderman_tweaks#1]
Make possible to prevent endermans to spawn at initial island at the end (Where is the Ender Dragon) bc I find annoying fight ender dragon while there're around endermans.

(Just on the initial island, not in all the end dimension)

**Comment by Natanaelel** [comment]
Good idea, I will try to do it tomorrow!

**Comment by Natanaelel** [comment]
Added in 0.2.0!

**Comment by MbtMarco** [comment]
Ty so much! 😁

**Comment by MbtMarco** [comment]
Just to know, can I add it to my modpack?

https://modrinth.com/modpack/travellers

I'll give credit with link in the changelog ( Next versione 0.0.7) and in the modlist.

**Comment by Natanaelel** [comment]
Yes, that's OK
