### ISSUE TITLE
Option to prevent attack Endermites

### ISSUE THREAD

**Issue by Weylend** [Natanaelel/enderman_tweaks#2]
It would be very cool if you added the option to prevent attack Endermites
So they cannot be used to make an Enderman farm

**Comment by Natanaelel** [comment]
Good idea. Will add in the coming days.

**Comment by Weylend** [comment]
Thanks for adding this but it doesn't seem to work
Endermen are completely broken with doesEndermiteAnger option enabled!!!

**Comment by Natanaelel** [comment]
Can you explain what you mean by "completely broken"?
What is happening?

**Comment by Weylend** [comment]
They just became passive

**Comment by Natanaelel** [comment]
~~At least they didn't attack endermites~~
Fixed in 0.3.1
